services:
  - type: web
    name: crm
    runtime: node
    buildCommand: npm install && npm run db:push && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: crm-db
          property: connectionString

databases:
  - name: crm-db
    plan: free
